name = "winery-list-backend"
main = "src/index.js"
compatibility_date = "2023-05-11"
kv_namespaces = [{ binding = "kv", id = "7936578a5c0a42e4b182fe01125e25a7", preview_id = "3d9f7524172044aa9b513efaaf0e6217" }]

[env.production]
route = "*wineries.jbcov.com/api*"

[triggers]
crons = ["0 19 * * *"]